spring:
  config:
    import: optional:application-secret.yaml

  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@ac-fntwfxt-shard-00-00.bbgx89l.mongodb.net:27017,ac-fntwfxt-shard-00-01.bbgx89l.mongodb.net:27017,ac-fntwfxt-shard-00-02.bbgx89l.mongodb.net:27017/teeup-db?ssl=true&replicaSet=atlas-owjper-shard-0&authSource=admin&retryWrites=true&w=majority

server:
  address: 0.0.0.0
  port: 8080

jwt:
  secretKey: buaabuaa
