spring:
  config:
    import: optional:application-secret.yaml

  data:
    mongodb:
      uri: mongodb+srv://NiceOnTest:<db_password>@niceoncluster0.bbgx89l.mongodb.net/?retryWrites=true&w=majority&appName=NiceOnCluster0

server:
  address: 0.0.0.0
  port: 8080

#프로필 사진 저장
file: 
  upload-dir: uploads/avatars
jwt:
  secretKey: buaabuaa